# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IPC-Open3-Utils
version:      0.7
version_from: lib/IPC/Open3/Utils.pm
installdirs:  site
requires:
    IO::Handle:                    0
    IO::Select:                    0
    IPC::Open3:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
