--- #YAML:1.0
name:                IPC-Open3-Utils
version:             0.8
abstract:            simple API encapsulating the most common open3() logic/uses including handling various corner cases and caveats
license:             ~
author:              
    - Daniel Muey <http://drmuey.com/cpan_contact.pl>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    IO::Handle:                    0
    IO::Select:                    0
    IPC::Open3:                    0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
